# core/ansi.nim
# Shared ANSI escape codes, generated by std/terminal (not hand-rolled escapes).
import std/terminal

const
  ClearScreen* = "\x1B[2J\x1B[H"
  ColorReset*  = ansiResetCode
  ColorBold*   = ansiStyleCode(styleBright)
  ColorGreen*  = ansiForegroundColorCode(fgGreen)
  ColorRed*    = ansiForegroundColorCode(fgRed)
  ColorYellow* = ansiForegroundColorCode(fgYellow)
  ColorBlue*   = ansiForegroundColorCode(fgBlue)
  ColorCyan*   = ansiForegroundColorCode(fgCyan)
  ColorPurple* = ansiForegroundColorCode(fgMagenta)
  ColorGrey*   = ansiForegroundColorCode(fgBlack, bright = true)
